### ISSUE TITLE
Constantes are redeclared

### ISSUE THREAD

**Issue by ToniCalfim** [ToniCalfim/fallingstars#4]
Note that **const** _stars_ and **const** _currentStar_ are declared twice: they are declared inside _function update()_ and also declared inside _function drawStars()_.

I think they could be declared only one time in a different place.

**Comment by llllOllOOll** [comment]
They aren't redeclared. They are in different Lexical Scope, they just can accessed inside where were define. If I didn't clear, let me know.

**Comment by ToniCalfim** [comment]
It is very clear, thanks.



But imagine if they always share the same value - I will check it later - I think they could be declared only one time in a different place.

**Comment by llllOllOOll** [comment]
We should think about scope! Don't care we have the same name of variable in different scope of code. Don't makes sense put it in a global scope. Whatever they have the same name, they are different. It's like a variable I in for loop, we can have it in many for-loop that we need.

**Comment by ToniCalfim** [comment]
Alright, I fully understand.
